// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {transport} from '../models';
import {snippets} from '../models';

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteSnippet(arg1:number):Promise<void>;

export function ForgetPairings():Promise<void>;

export function GetPairing():Promise<transport.PairingSnapshot>;

export function GetSnippets():Promise<snippets.Snapshot>;

export function GetStatus():Promise<transport.Status>;

export function ReplaceDictionary(arg1:Array<string>):Promise<void>;

export function SaveCategory(arg1:snippets.Category):Promise<number>;

export function SaveSnippet(arg1:snippets.Snippet):Promise<number>;
