// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteSnippet(arg1) {
  return window['go']['main']['App']['DeleteSnippet'](arg1);
}

export function ForgetPairings() {
  return window['go']['main']['App']['ForgetPairings']();
}

export function GetPairing() {
  return window['go']['main']['App']['GetPairing']();
}

export function GetSnippets() {
  return window['go']['main']['App']['GetSnippets']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ReplaceDictionary(arg1) {
  return window['go']['main']['App']['ReplaceDictionary'](arg1);
}

export function SaveCategory(arg1) {
  return window['go']['main']['App']['SaveCategory'](arg1);
}

export function SaveSnippet(arg1) {
  return window['go']['main']['App']['SaveSnippet'](arg1);
}
